/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Concept;
import io.swagger.client.model.MultipleItemsForVisualization;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AllOfConceptGraphConceptGraph
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class AllOfConceptGraphConceptGraph extends MultipleItemsForVisualization {
  @SerializedName("concepts")
  private List<Concept> concepts = null;

  @SerializedName("links")
  private List<Object> links = null;

  public AllOfConceptGraphConceptGraph concepts(List<Concept> concepts) {
    this.concepts = concepts;
    return this;
  }

  public AllOfConceptGraphConceptGraph addConceptsItem(Concept conceptsItem) {
    if (this.concepts == null) {
      this.concepts = new ArrayList<Concept>();
    }
    this.concepts.add(conceptsItem);
    return this;
  }

   /**
   * Get concepts
   * @return concepts
  **/
  @Schema(description = "")
  public List<Concept> getConcepts() {
    return concepts;
  }

  public void setConcepts(List<Concept> concepts) {
    this.concepts = concepts;
  }

  public AllOfConceptGraphConceptGraph links(List<Object> links) {
    this.links = links;
    return this;
  }

  public AllOfConceptGraphConceptGraph addLinksItem(Object linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Object>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public List<Object> getLinks() {
    return links;
  }

  public void setLinks(List<Object> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllOfConceptGraphConceptGraph allOfConceptGraphConceptGraph = (AllOfConceptGraphConceptGraph) o;
    return Objects.equals(this.concepts, allOfConceptGraphConceptGraph.concepts) &&
        Objects.equals(this.links, allOfConceptGraphConceptGraph.links) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(concepts, links, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllOfConceptGraphConceptGraph {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    concepts: ").append(toIndentedString(concepts)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
