/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AnnotationStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class AnnotationStats {
  @SerializedName("iFrom")
  private Integer iFrom = null;

  @SerializedName("iTo")
  private Integer iTo = null;

  @SerializedName("normForm")
  private String normForm = null;

  @SerializedName("synsetIds")
  private List<Integer> synsetIds = null;

  public AnnotationStats iFrom(Integer iFrom) {
    this.iFrom = iFrom;
    return this;
  }

   /**
   * Get iFrom
   * @return iFrom
  **/
  @Schema(description = "")
  public Integer getIFrom() {
    return iFrom;
  }

  public void setIFrom(Integer iFrom) {
    this.iFrom = iFrom;
  }

  public AnnotationStats iTo(Integer iTo) {
    this.iTo = iTo;
    return this;
  }

   /**
   * Get iTo
   * @return iTo
  **/
  @Schema(description = "")
  public Integer getITo() {
    return iTo;
  }

  public void setITo(Integer iTo) {
    this.iTo = iTo;
  }

  public AnnotationStats normForm(String normForm) {
    this.normForm = normForm;
    return this;
  }

   /**
   * Get normForm
   * @return normForm
  **/
  @Schema(description = "")
  public String getNormForm() {
    return normForm;
  }

  public void setNormForm(String normForm) {
    this.normForm = normForm;
  }

  public AnnotationStats synsetIds(List<Integer> synsetIds) {
    this.synsetIds = synsetIds;
    return this;
  }

  public AnnotationStats addSynsetIdsItem(Integer synsetIdsItem) {
    if (this.synsetIds == null) {
      this.synsetIds = new ArrayList<Integer>();
    }
    this.synsetIds.add(synsetIdsItem);
    return this;
  }

   /**
   * Get synsetIds
   * @return synsetIds
  **/
  @Schema(description = "")
  public List<Integer> getSynsetIds() {
    return synsetIds;
  }

  public void setSynsetIds(List<Integer> synsetIds) {
    this.synsetIds = synsetIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnotationStats annotationStats = (AnnotationStats) o;
    return Objects.equals(this.iFrom, annotationStats.iFrom) &&
        Objects.equals(this.iTo, annotationStats.iTo) &&
        Objects.equals(this.normForm, annotationStats.normForm) &&
        Objects.equals(this.synsetIds, annotationStats.synsetIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iFrom, iTo, normForm, synsetIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnotationStats {\n");
    
    sb.append("    iFrom: ").append(toIndentedString(iFrom)).append("\n");
    sb.append("    iTo: ").append(toIndentedString(iTo)).append("\n");
    sb.append("    normForm: ").append(toIndentedString(normForm)).append("\n");
    sb.append("    synsetIds: ").append(toIndentedString(synsetIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
