/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CategorizationKeywords;
import io.swagger.client.model.CategorizationObject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Categorization
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class Categorization {
  @SerializedName("categories")
  private List<CategorizationObject> categories = null;

  @SerializedName("keywords")
  private List<CategorizationKeywords> keywords = null;

  public Categorization categories(List<CategorizationObject> categories) {
    this.categories = categories;
    return this;
  }

  public Categorization addCategoriesItem(CategorizationObject categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<CategorizationObject>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @Schema(description = "")
  public List<CategorizationObject> getCategories() {
    return categories;
  }

  public void setCategories(List<CategorizationObject> categories) {
    this.categories = categories;
  }

  public Categorization keywords(List<CategorizationKeywords> keywords) {
    this.keywords = keywords;
    return this;
  }

  public Categorization addKeywordsItem(CategorizationKeywords keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<CategorizationKeywords>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @Schema(description = "")
  public List<CategorizationKeywords> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<CategorizationKeywords> keywords) {
    this.keywords = keywords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Categorization categorization = (Categorization) o;
    return Objects.equals(this.categories, categorization.categories) &&
        Objects.equals(this.keywords, categorization.keywords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categories, keywords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Categorization {\n");
    
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
