/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TrendingScore;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Category
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class Category {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("parentUri")
  private String parentUri = null;

  @SerializedName("childrenUris")
  private List<String> childrenUris = null;

  @SerializedName("trendingScore")
  private TrendingScore trendingScore = null;

  @SerializedName("count")
  private Integer count = null;

  public Category uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Category label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Category parentUri(String parentUri) {
    this.parentUri = parentUri;
    return this;
  }

   /**
   * Get parentUri
   * @return parentUri
  **/
  @Schema(description = "")
  public String getParentUri() {
    return parentUri;
  }

  public void setParentUri(String parentUri) {
    this.parentUri = parentUri;
  }

  public Category childrenUris(List<String> childrenUris) {
    this.childrenUris = childrenUris;
    return this;
  }

  public Category addChildrenUrisItem(String childrenUrisItem) {
    if (this.childrenUris == null) {
      this.childrenUris = new ArrayList<String>();
    }
    this.childrenUris.add(childrenUrisItem);
    return this;
  }

   /**
   * Get childrenUris
   * @return childrenUris
  **/
  @Schema(description = "")
  public List<String> getChildrenUris() {
    return childrenUris;
  }

  public void setChildrenUris(List<String> childrenUris) {
    this.childrenUris = childrenUris;
  }

  public Category trendingScore(TrendingScore trendingScore) {
    this.trendingScore = trendingScore;
    return this;
  }

   /**
   * Get trendingScore
   * @return trendingScore
  **/
  @Schema(description = "")
  public TrendingScore getTrendingScore() {
    return trendingScore;
  }

  public void setTrendingScore(TrendingScore trendingScore) {
    this.trendingScore = trendingScore;
  }

  public Category count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return Objects.equals(this.uri, category.uri) &&
        Objects.equals(this.label, category.label) &&
        Objects.equals(this.parentUri, category.parentUri) &&
        Objects.equals(this.childrenUris, category.childrenUris) &&
        Objects.equals(this.trendingScore, category.trendingScore) &&
        Objects.equals(this.count, category.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, label, parentUri, childrenUris, trendingScore, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    parentUri: ").append(toIndentedString(parentUri)).append("\n");
    sb.append("    childrenUris: ").append(toIndentedString(childrenUris)).append("\n");
    sb.append("    trendingScore: ").append(toIndentedString(trendingScore)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
