/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ExtractArticleInfoObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class ExtractArticleInfoObject {
  @SerializedName("url")
  private String url = null;

  @SerializedName("anchorText")
  private String anchorText = null;

  public ExtractArticleInfoObject url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ExtractArticleInfoObject anchorText(String anchorText) {
    this.anchorText = anchorText;
    return this;
  }

   /**
   * Get anchorText
   * @return anchorText
  **/
  @Schema(description = "")
  public String getAnchorText() {
    return anchorText;
  }

  public void setAnchorText(String anchorText) {
    this.anchorText = anchorText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExtractArticleInfoObject extractArticleInfoObject = (ExtractArticleInfoObject) o;
    return Objects.equals(this.url, extractArticleInfoObject.url) &&
        Objects.equals(this.anchorText, extractArticleInfoObject.anchorText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, anchorText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExtractArticleInfoObject {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    anchorText: ").append(toIndentedString(anchorText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
