/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Articles;
import io.swagger.client.model.CategoryAggr;
import io.swagger.client.model.ConceptAggr;
import io.swagger.client.model.ConceptGraph;
import io.swagger.client.model.KeywordAggr;
import io.swagger.client.model.RecentActivityArticles;
import io.swagger.client.model.RecentActivityArticlesRecentActivityArticles;
import io.swagger.client.model.SourceAggr;
import io.swagger.client.model.TimeAggr;
import io.swagger.client.model.UriWgtList;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2002
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class InlineResponse2002 extends Articles {
  @SerializedName("uriWgtList")
  private Object uriWgtList = null;

  @SerializedName("conceptAggr")
  private Object conceptAggr = null;

  @SerializedName("keywordAggr")
  private Object keywordAggr = null;

  @SerializedName("timeAggr")
  private Object timeAggr = null;

  @SerializedName("sourceAggr")
  private Object sourceAggr = null;

  @SerializedName("conceptGraph")
  private Object conceptGraph = null;

  @SerializedName("categoryAggr")
  private Object categoryAggr = null;

  @SerializedName("recentActivityArticles")
  private RecentActivityArticlesRecentActivityArticles recentActivityArticles = null;

  public InlineResponse2002 uriWgtList(Object uriWgtList) {
    this.uriWgtList = uriWgtList;
    return this;
  }

   /**
   * Get uriWgtList
   * @return uriWgtList
  **/
  @Schema(description = "")
  public Object getUriWgtList() {
    return uriWgtList;
  }

  public void setUriWgtList(Object uriWgtList) {
    this.uriWgtList = uriWgtList;
  }

  public InlineResponse2002 conceptAggr(Object conceptAggr) {
    this.conceptAggr = conceptAggr;
    return this;
  }

   /**
   * Get conceptAggr
   * @return conceptAggr
  **/
  @Schema(description = "")
  public Object getConceptAggr() {
    return conceptAggr;
  }

  public void setConceptAggr(Object conceptAggr) {
    this.conceptAggr = conceptAggr;
  }

  public InlineResponse2002 keywordAggr(Object keywordAggr) {
    this.keywordAggr = keywordAggr;
    return this;
  }

   /**
   * Get keywordAggr
   * @return keywordAggr
  **/
  @Schema(description = "")
  public Object getKeywordAggr() {
    return keywordAggr;
  }

  public void setKeywordAggr(Object keywordAggr) {
    this.keywordAggr = keywordAggr;
  }

  public InlineResponse2002 timeAggr(Object timeAggr) {
    this.timeAggr = timeAggr;
    return this;
  }

   /**
   * Get timeAggr
   * @return timeAggr
  **/
  @Schema(description = "")
  public Object getTimeAggr() {
    return timeAggr;
  }

  public void setTimeAggr(Object timeAggr) {
    this.timeAggr = timeAggr;
  }

  public InlineResponse2002 sourceAggr(Object sourceAggr) {
    this.sourceAggr = sourceAggr;
    return this;
  }

   /**
   * Get sourceAggr
   * @return sourceAggr
  **/
  @Schema(description = "")
  public Object getSourceAggr() {
    return sourceAggr;
  }

  public void setSourceAggr(Object sourceAggr) {
    this.sourceAggr = sourceAggr;
  }

  public InlineResponse2002 conceptGraph(Object conceptGraph) {
    this.conceptGraph = conceptGraph;
    return this;
  }

   /**
   * Get conceptGraph
   * @return conceptGraph
  **/
  @Schema(description = "")
  public Object getConceptGraph() {
    return conceptGraph;
  }

  public void setConceptGraph(Object conceptGraph) {
    this.conceptGraph = conceptGraph;
  }

  public InlineResponse2002 categoryAggr(Object categoryAggr) {
    this.categoryAggr = categoryAggr;
    return this;
  }

   /**
   * Get categoryAggr
   * @return categoryAggr
  **/
  @Schema(description = "")
  public Object getCategoryAggr() {
    return categoryAggr;
  }

  public void setCategoryAggr(Object categoryAggr) {
    this.categoryAggr = categoryAggr;
  }

  public InlineResponse2002 recentActivityArticles(RecentActivityArticlesRecentActivityArticles recentActivityArticles) {
    this.recentActivityArticles = recentActivityArticles;
    return this;
  }

   /**
   * Get recentActivityArticles
   * @return recentActivityArticles
  **/
  @Schema(description = "")
  public RecentActivityArticlesRecentActivityArticles getRecentActivityArticles() {
    return recentActivityArticles;
  }

  public void setRecentActivityArticles(RecentActivityArticlesRecentActivityArticles recentActivityArticles) {
    this.recentActivityArticles = recentActivityArticles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.uriWgtList, inlineResponse2002.uriWgtList) &&
        Objects.equals(this.conceptAggr, inlineResponse2002.conceptAggr) &&
        Objects.equals(this.keywordAggr, inlineResponse2002.keywordAggr) &&
        Objects.equals(this.timeAggr, inlineResponse2002.timeAggr) &&
        Objects.equals(this.sourceAggr, inlineResponse2002.sourceAggr) &&
        Objects.equals(this.conceptGraph, inlineResponse2002.conceptGraph) &&
        Objects.equals(this.categoryAggr, inlineResponse2002.categoryAggr) &&
        Objects.equals(this.recentActivityArticles, inlineResponse2002.recentActivityArticles) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uriWgtList, conceptAggr, keywordAggr, timeAggr, sourceAggr, conceptGraph, categoryAggr, recentActivityArticles, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    uriWgtList: ").append(toIndentedString(uriWgtList)).append("\n");
    sb.append("    conceptAggr: ").append(toIndentedString(conceptAggr)).append("\n");
    sb.append("    keywordAggr: ").append(toIndentedString(keywordAggr)).append("\n");
    sb.append("    timeAggr: ").append(toIndentedString(timeAggr)).append("\n");
    sb.append("    sourceAggr: ").append(toIndentedString(sourceAggr)).append("\n");
    sb.append("    conceptGraph: ").append(toIndentedString(conceptGraph)).append("\n");
    sb.append("    categoryAggr: ").append(toIndentedString(categoryAggr)).append("\n");
    sb.append("    recentActivityArticles: ").append(toIndentedString(recentActivityArticles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
