/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse20010RecentActivityEventsEventInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20010RecentActivityEvents
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class InlineResponse20010RecentActivityEvents {
  @SerializedName("activity")
  private List<String> activity = null;

  @SerializedName("eventInfo")
  private InlineResponse20010RecentActivityEventsEventInfo eventInfo = null;

  public InlineResponse20010RecentActivityEvents activity(List<String> activity) {
    this.activity = activity;
    return this;
  }

  public InlineResponse20010RecentActivityEvents addActivityItem(String activityItem) {
    if (this.activity == null) {
      this.activity = new ArrayList<String>();
    }
    this.activity.add(activityItem);
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  @Schema(description = "")
  public List<String> getActivity() {
    return activity;
  }

  public void setActivity(List<String> activity) {
    this.activity = activity;
  }

  public InlineResponse20010RecentActivityEvents eventInfo(InlineResponse20010RecentActivityEventsEventInfo eventInfo) {
    this.eventInfo = eventInfo;
    return this;
  }

   /**
   * Get eventInfo
   * @return eventInfo
  **/
  @Schema(description = "")
  public InlineResponse20010RecentActivityEventsEventInfo getEventInfo() {
    return eventInfo;
  }

  public void setEventInfo(InlineResponse20010RecentActivityEventsEventInfo eventInfo) {
    this.eventInfo = eventInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010RecentActivityEvents inlineResponse20010RecentActivityEvents = (InlineResponse20010RecentActivityEvents) o;
    return Objects.equals(this.activity, inlineResponse20010RecentActivityEvents.activity) &&
        Objects.equals(this.eventInfo, inlineResponse20010RecentActivityEvents.eventInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activity, eventInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010RecentActivityEvents {\n");
    
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    eventInfo: ").append(toIndentedString(eventInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
