/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.InlineResponse2001TopicCategories;
import io.swagger.client.model.InlineResponse2001TopicConcepts;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2001Topic
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class InlineResponse2001Topic {
  @SerializedName("concepts")
  private List<InlineResponse2001TopicConcepts> concepts = null;

  @SerializedName("categories")
  private List<InlineResponse2001TopicCategories> categories = null;

  public InlineResponse2001Topic concepts(List<InlineResponse2001TopicConcepts> concepts) {
    this.concepts = concepts;
    return this;
  }

  public InlineResponse2001Topic addConceptsItem(InlineResponse2001TopicConcepts conceptsItem) {
    if (this.concepts == null) {
      this.concepts = new ArrayList<InlineResponse2001TopicConcepts>();
    }
    this.concepts.add(conceptsItem);
    return this;
  }

   /**
   * Get concepts
   * @return concepts
  **/
  @Schema(description = "")
  public List<InlineResponse2001TopicConcepts> getConcepts() {
    return concepts;
  }

  public void setConcepts(List<InlineResponse2001TopicConcepts> concepts) {
    this.concepts = concepts;
  }

  public InlineResponse2001Topic categories(List<InlineResponse2001TopicCategories> categories) {
    this.categories = categories;
    return this;
  }

  public InlineResponse2001Topic addCategoriesItem(InlineResponse2001TopicCategories categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<InlineResponse2001TopicCategories>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @Schema(description = "")
  public List<InlineResponse2001TopicCategories> getCategories() {
    return categories;
  }

  public void setCategories(List<InlineResponse2001TopicCategories> categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Topic inlineResponse2001Topic = (InlineResponse2001Topic) o;
    return Objects.equals(this.concepts, inlineResponse2001Topic.concepts) &&
        Objects.equals(this.categories, inlineResponse2001Topic.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(concepts, categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Topic {\n");
    
    sb.append("    concepts: ").append(toIndentedString(concepts)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
