/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LocAggr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class LocAggr {
  @SerializedName("keywordAggr")
  private AllOfLocAggrKeywordAggr keywordAggr = null;

  public LocAggr keywordAggr(AllOfLocAggrKeywordAggr keywordAggr) {
    this.keywordAggr = keywordAggr;
    return this;
  }

   /**
   * Get keywordAggr
   * @return keywordAggr
  **/
  @Schema(description = "")
  public AllOfLocAggrKeywordAggr getKeywordAggr() {
    return keywordAggr;
  }

  public void setKeywordAggr(AllOfLocAggrKeywordAggr keywordAggr) {
    this.keywordAggr = keywordAggr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocAggr locAggr = (LocAggr) o;
    return Objects.equals(this.keywordAggr, locAggr.keywordAggr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keywordAggr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocAggr {\n");
    
    sb.append("    keywordAggr: ").append(toIndentedString(keywordAggr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
