/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Query1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class Query1 {
  @SerializedName("conceptUri")
  private List<String> conceptUri = null;

  @SerializedName("sourceUri")
  private List<String> sourceUri = null;

  @SerializedName("sourceLocationUri")
  private List<String> sourceLocationUri = null;

  @SerializedName("locationUri")
  private List<String> locationUri = null;

  public Query1 conceptUri(List<String> conceptUri) {
    this.conceptUri = conceptUri;
    return this;
  }

  public Query1 addConceptUriItem(String conceptUriItem) {
    if (this.conceptUri == null) {
      this.conceptUri = new ArrayList<String>();
    }
    this.conceptUri.add(conceptUriItem);
    return this;
  }

   /**
   * Get conceptUri
   * @return conceptUri
  **/
  @Schema(description = "")
  public List<String> getConceptUri() {
    return conceptUri;
  }

  public void setConceptUri(List<String> conceptUri) {
    this.conceptUri = conceptUri;
  }

  public Query1 sourceUri(List<String> sourceUri) {
    this.sourceUri = sourceUri;
    return this;
  }

  public Query1 addSourceUriItem(String sourceUriItem) {
    if (this.sourceUri == null) {
      this.sourceUri = new ArrayList<String>();
    }
    this.sourceUri.add(sourceUriItem);
    return this;
  }

   /**
   * Get sourceUri
   * @return sourceUri
  **/
  @Schema(description = "")
  public List<String> getSourceUri() {
    return sourceUri;
  }

  public void setSourceUri(List<String> sourceUri) {
    this.sourceUri = sourceUri;
  }

  public Query1 sourceLocationUri(List<String> sourceLocationUri) {
    this.sourceLocationUri = sourceLocationUri;
    return this;
  }

  public Query1 addSourceLocationUriItem(String sourceLocationUriItem) {
    if (this.sourceLocationUri == null) {
      this.sourceLocationUri = new ArrayList<String>();
    }
    this.sourceLocationUri.add(sourceLocationUriItem);
    return this;
  }

   /**
   * Get sourceLocationUri
   * @return sourceLocationUri
  **/
  @Schema(description = "")
  public List<String> getSourceLocationUri() {
    return sourceLocationUri;
  }

  public void setSourceLocationUri(List<String> sourceLocationUri) {
    this.sourceLocationUri = sourceLocationUri;
  }

  public Query1 locationUri(List<String> locationUri) {
    this.locationUri = locationUri;
    return this;
  }

  public Query1 addLocationUriItem(String locationUriItem) {
    if (this.locationUri == null) {
      this.locationUri = new ArrayList<String>();
    }
    this.locationUri.add(locationUriItem);
    return this;
  }

   /**
   * Get locationUri
   * @return locationUri
  **/
  @Schema(description = "")
  public List<String> getLocationUri() {
    return locationUri;
  }

  public void setLocationUri(List<String> locationUri) {
    this.locationUri = locationUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Query1 query1 = (Query1) o;
    return Objects.equals(this.conceptUri, query1.conceptUri) &&
        Objects.equals(this.sourceUri, query1.sourceUri) &&
        Objects.equals(this.sourceLocationUri, query1.sourceLocationUri) &&
        Objects.equals(this.locationUri, query1.locationUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conceptUri, sourceUri, sourceLocationUri, locationUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Query1 {\n");
    
    sb.append("    conceptUri: ").append(toIndentedString(conceptUri)).append("\n");
    sb.append("    sourceUri: ").append(toIndentedString(sourceUri)).append("\n");
    sb.append("    sourceLocationUri: ").append(toIndentedString(sourceLocationUri)).append("\n");
    sb.append("    locationUri: ").append(toIndentedString(locationUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
