/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RecentActivityArticlesRecentActivityArticles
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class RecentActivityArticlesRecentActivityArticles {
  @SerializedName("currTime")
  private String currTime = null;

  @SerializedName("activity")
  private List<Object> activity = null;

  public RecentActivityArticlesRecentActivityArticles currTime(String currTime) {
    this.currTime = currTime;
    return this;
  }

   /**
   * Get currTime
   * @return currTime
  **/
  @Schema(description = "")
  public String getCurrTime() {
    return currTime;
  }

  public void setCurrTime(String currTime) {
    this.currTime = currTime;
  }

  public RecentActivityArticlesRecentActivityArticles activity(List<Object> activity) {
    this.activity = activity;
    return this;
  }

  public RecentActivityArticlesRecentActivityArticles addActivityItem(Object activityItem) {
    if (this.activity == null) {
      this.activity = new ArrayList<Object>();
    }
    this.activity.add(activityItem);
    return this;
  }

   /**
   * Get activity
   * @return activity
  **/
  @Schema(description = "")
  public List<Object> getActivity() {
    return activity;
  }

  public void setActivity(List<Object> activity) {
    this.activity = activity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecentActivityArticlesRecentActivityArticles recentActivityArticlesRecentActivityArticles = (RecentActivityArticlesRecentActivityArticles) o;
    return Objects.equals(this.currTime, recentActivityArticlesRecentActivityArticles.currTime) &&
        Objects.equals(this.activity, recentActivityArticlesRecentActivityArticles.activity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currTime, activity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecentActivityArticlesRecentActivityArticles {\n");
    
    sb.append("    currTime: ").append(toIndentedString(currTime)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
