/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TimeAggr
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-03T18:38:48.218840542Z[GMT]")

public class TimeAggr {
  @SerializedName("timeAggr")
  private AllOfTimeAggrTimeAggr timeAggr = null;

  public TimeAggr timeAggr(AllOfTimeAggrTimeAggr timeAggr) {
    this.timeAggr = timeAggr;
    return this;
  }

   /**
   * Get timeAggr
   * @return timeAggr
  **/
  @Schema(description = "")
  public AllOfTimeAggrTimeAggr getTimeAggr() {
    return timeAggr;
  }

  public void setTimeAggr(AllOfTimeAggrTimeAggr timeAggr) {
    this.timeAggr = timeAggr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeAggr timeAggr = (TimeAggr) o;
    return Objects.equals(this.timeAggr, timeAggr.timeAggr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeAggr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeAggr {\n");
    
    sb.append("    timeAggr: ").append(toIndentedString(timeAggr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
