/*
 * Event Registry REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OtherApi
 */
@Ignore
public class OtherApiTest {

    private final OtherApi api = new OtherApi();

    /**
     * Identify a recent event that best matches your input text and return a list of articles about the event
     *
     * Given a paragraph or a longer text, the API endpoint can provide you the recent event that best matches the text. The return value will contain the URI of the event that is most related to the text and the value will contain the list of articles about the event. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEventForTextenqueueRequestTest() throws Exception {
        String apiKey = null;
        String text = null;
        String lang = null;
        String resultType = null;
        String response = api.getEventForTextenqueueRequest(apiKey, text, lang, resultType);

        // TODO: test validations
    }
}
